version: "3.8"

services:
  pgdb:
    image: postgres
    container_name: pg
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - backend
  rabbitmq:
    image: rabbitmq
    container_name: rmq
    ports:
      - "5672:5672"
    networks:
      - backend
  celery:
    build:
      context: .
      dockerfile: ./app/docker/celery/Dockerfile
    container_name: celery
    env_file:
      - .env
    depends_on:
      - pgdb
      - rabbitmq
    networks:
      - backend
  fastapi:
    build:
      context: .
      dockerfile: ./app/docker/fastapi/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgdb
      - rabbitmq
    networks:
      - backend

networks:
  backend:
    driver: bridge